# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 08:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone_no', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_location', models.CharField(max_length=150)),
                ('job_description', models.CharField(max_length=180)),
                ('job_title', models.CharField(max_length=20)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clockwork.Employer')),
            ],
        ),
        migrations.CreateModel(
            name='Jobseeker',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', models.CharField(max_length=12)),
                ('home_location', models.CharField(max_length=150)),
                ('industry', models.CharField(choices=[('CON', 'Construction'), ('PRO', 'Promotions'), ('EV', 'Events'), ('BAR', 'Barwork'), ('GAR', 'Gardening'), ('CLE', 'Cleaning'), ('TRA', 'Transport')], max_length=12)),
                ('other_industry', models.CharField(max_length=150)),
                ('id_number', models.CharField(max_length=13, primary_key=True, serialize=False)),
            ],
        ),
    ]
