# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clockwork', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='wage',
            field=models.CharField(default=0, max_length=6),
        ),
    ]
