# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 11:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clockwork', '0002_job_wage'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='job',
            name='time',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
