# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clockwork', '0003_auto_20160702_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='jobs',
            field=models.ManyToManyField(to='clockwork.Job'),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='industry',
            field=models.CharField(choices=[('Construction', 'Construction'), ('Promotions', 'Promotions'), ('Events', 'Events'), ('Barwork', 'Barwork'), ('Gardener', 'Gardening'), ('Cleaning', 'Cleaning'), ('Transport', 'Transport')], max_length=12),
        ),
    ]
